HOTFIX: make the discord_bot work again. Honeycomb#add_alert broke it (#1047)
* HOTFIX: make the discord_bot work again. Honeycomb#add_alert broke it

I forgot that anything required by the DiscordBot can't rely on being run
inside the Rails env. The bot hasn't been able to start for the past week
due to the following error:

```
bundler: failed to load command: bin/discord_bot (bin/discord_bot)

/app/config/initializers/honeycomb.rb:4:in `block in <top (required)>': undefined method `application' for Rails:Module (NoMethodError)

    from /app/vendor/bundle/ruby/3.0.0/gems/honeycomb-beeline-2.8.2/lib/honeycomb-beeline.rb:34:in `block in configure'
    from <internal:kernel>:90:in `tap'
    from /app/vendor/bundle/ruby/3.0.0/gems/honeycomb-beeline-2.8.2/lib/honeycomb-beeline.rb:33:in `configure'
    from /app/config/initializers/honeycomb.rb:3:in `<top (required)>'
    from /app/lib/discord_bot.rb:12:in `require_relative'
    from /app/lib/discord_bot.rb:12:in `<top (required)>'
    from bin/discord_bot:4:in `require'
    ...
```

* Clarify the 3rd party vs internal `require` organization