Specs cleanup: compile Webpacker once per run / fix deprecation warnings (#1023)
* Speed up specs by compiling Webpacker once

* HAX logging. Revert me.

One spec is failing in CI but not locally. Hard to debug. See if this helps get to the issue
and then revert this.

* Revert "HAX logging. Revert me."

This reverts commit 4ae10c8f1287c32ba8047d6ef104adc362edae47.

* Mimic what the other specs do by checking the page contents in two steps.

No clue why one spec was failing in CI but worked locally. Just adding
the logging made it pass. So maybe it's a timing thing.

* Fix Broswer console logs.

Gets rid of this warning
WARN Selenium [DEPRECATION] Manager#logs is deprecated. Use Chrome::Driver#logs instead.

* Gets rid of DEPRECATION warning

WARN Selenium [DEPRECATION] [:desired_capabilities] :desired_capabilities as a parameter for driver initialization is deprecated. Use :capabilities with an Array value of capabilities/options if necessary instead.

* Attempt to fix failing spec

What I think is happening is that a HoneycombJS span is coming through
after the LtiLaunch is cleaned up b/c of a timing issue. That results
in this error:

LtiAuthentication::WardenStrategy couldn't find LtiLaunch using state value
Rack app ("POST /honeycomb_js/send_span" - (127.0.0.1)): #<NoMethodError: undefined method `[]' for nil:NilClass>

This "undefined method `[]' for nil:NilClass" error is something we see quite a bit so I dug into
what happens when the LtiAuthentication middleware hits the :forbidden path and realizing
something must have changed at some point b/c passing the symbol to custom! doesn't seem to
work. Changed it to mimic what this spec does:
https://github.com/wardencommunity/warden/blob/8b44aa4dd8ff4bfcc0e7257dea095789ffb58690/spec/warden/manager_spec.rb#L283

Tested by putting a state=fakestatevalue in an LtiLaunchable endpoint. E.g.
https://platformweb/course_project_versions/38/project_submissions/167/edit?state=asfdasdf