Upgrade ruby 2.6 to ruby 2.7. (#644)
* Upgrade ruby 2.6 to ruby 2.7.

In the specs, a `can't modify frozen String: ""` error was happening.
This fixes that: https://github.com/bebraven/rubycas-server-core/pull/3

On a Mac, run the following to upgrade:
$ xcode-select --install
- Fixes: "Error: python@3.9: the bottle needs the Apple Command Line Tools to be installed."

$ rvm install ruby-2.7.2
$ docker-compose down
$ docker volume rm platform_vendor-bundle
$ docker volume rm platform_node-modules
$ docker-compose build --no-cache && docker-compose up -d
$ docker-compose up -d --force-recreate --build

Specs should pass at this point.

TODO: grep the code for `to_s` and make sure subsequent code operating on those
strings dont try to modify them. Then make sure Sentry is configured and spot
check all the functionality of the site. Make sure exceptions aren't happening.

* Update ref for `rubycas-server-core` gem to get Ruby 2.7 fix

* Don't throw exceptions for missing Honeycomb name field

I don't know how to reproduce this, but I've seen this error
and it's noise:

-----
NoMethodError
undefined method `start_with?' for nil:NilClass

lib/filter_logging.rb in filter_honeycomb_data at line 143

    # These are values coming from HoneycombJsController generated spans
    # from Boomerang payloads.
    if fields['name'].start_with?('js.')
      if fields.has_key?("#{BOOMERANG_FIELD_PREFIX}.request.query_string")

------

https://sentry.io/organizations/braven-pr/issues/2514378350/?project=5673406&query=is%3Aunresolved

* Handle weird URIs sent from Boomerang.

When doing the pre-survey, this URI was sent in a Boomerang field
which the URI class can't parse:

https://braven.tfaforms.net/api_v2/datasets/d08142c5-1459-47cb-8305-3143c86cb146?query=Sanbor&undefined=%%undefined%%

The error was:

URI::InvalidURIError (invalid percent escape: %%u):

app/controllers/honeycomb_js_controller.rb:98:in `translate_boomerang_fields'

Addressable::URI.parse() seems to work. Verified in console.

Sentry link: https://sentry.io/organizations/braven-pr/issues/2514378321/?project=5673406