Hotfix to allow editing users with no Salesforce ID in the Admin dash. (#716)
A blank salesforce_id is set in the database as the empty string.
The uniqueness contstraint treats that is a value so the second
admin user we edit will fail with:

ActiveRecord::RecordNotUnique
PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_users_on_salesforce_id"
DETAIL:  Key (salesforce_id)=() already exists.
PG::UniqueViolation
ERROR:  duplicate key value violates unique constraint "index_users_on_salesforce_id"
DETAIL:  Key (salesforce_id)=() already exists.